defmodule PhoenixLite.HostProject do
  @moduledoc """
  Introspects the host project the installer is being applied to, returning
  the values needed to render the templated `runtime.exs`.
  """

  @sentinel "# Generated by phoenix_lite"

  @doc "Sentinel comment placed in the templated `runtime.exs`."
  def sentinel, do: @sentinel

  @doc """
  Returns `{:ok, info}` for a Phoenix host project, where `info` contains the
  `:otp_app` and `:endpoint_module` needed to render the template.

  Returns `{:error, reason}` if the host project does not declare a `:phoenix`
  dependency.
  """
  @spec inspect(Igniter.t()) ::
          {:ok, %{otp_app: atom(), endpoint_module: String.t()}}
          | {:error, String.t()}
  def inspect(igniter) do
    if Igniter.Project.Deps.has_dep?(igniter, :phoenix) do
      otp_app = Igniter.Project.Application.app_name(igniter)
      {:ok, %{otp_app: otp_app, endpoint_module: endpoint_module(otp_app)}}
    else
      {:error,
       "phoenix_lite expects a Phoenix project but `:phoenix` was not found in the host project's deps."}
    end
  end

  defp endpoint_module(otp_app) do
    "#{otp_app |> to_string() |> Macro.camelize()}Web.Endpoint"
  end
end
