defmodule Mix.Tasks.PhoenixProdmin.InstallTest do
  use ExUnit.Case
  import Igniter.Test

  @original_runtime """
  import Config

  if config_env() == :prod do
    config :myapp, MyappWeb.Endpoint, server: true
  end
  """

  defp phoenix_project(extra_files \\ %{}) do
    files =
      Map.merge(
        %{
          "mix.exs" => """
          defmodule Myapp.MixProject do
            use Mix.Project

            def project do
              [
                app: :myapp,
                version: "0.1.0",
                elixir: "~> 1.17",
                start_permanent: Mix.env() == :prod,
                deps: deps()
              ]
            end

            def application do
              [
                extra_applications: [:logger]
              ]
            end

            defp deps do
              [
                {:phoenix, "~> 1.7"}
              ]
            end
          end
          """,
          "config/runtime.exs" => @original_runtime
        },
        extra_files
      )

    test_project(app_name: :myapp, files: files)
  end

  describe "fresh install" do
    test "writes the templated runtime.exs and a backup" do
      igniter =
        phoenix_project()
        |> Igniter.compose_task("phoenix_prodmin.install", [])
        |> apply_igniter!()

      runtime = read(igniter, "config/runtime.exs")
      backup = read(igniter, "config/.runtime.exs.bak")

      assert runtime =~ "# Generated by phoenix_prodmin"
      assert runtime =~ "config :myapp, MyappWeb.Endpoint"
      assert runtime =~ "ip: {0, 0, 0, 0}"
      assert runtime =~ "host: \"0.0.0.0\""
      assert runtime =~ "server: true"
      assert runtime =~ ~r/secret_key_base: "[^"]+"/
      refute runtime =~ "https:"

      assert backup == @original_runtime
    end

    test "secret_key_base is non-empty and varies between runs" do
      key1 = phoenix_project() |> install_and_extract_secret()
      key2 = phoenix_project() |> install_and_extract_secret()

      assert byte_size(key1) > 32
      refute key1 == key2
    end

    test "--no-backup skips the backup file" do
      igniter =
        phoenix_project()
        |> Igniter.compose_task("phoenix_prodmin.install", ["--no-backup"])
        |> apply_igniter!()

      assert read(igniter, "config/runtime.exs") =~ "# Generated by phoenix_prodmin"
      refute Igniter.exists?(igniter, "config/.runtime.exs.bak")
    end
  end

  describe "idempotency" do
    test "second run without --force is a no-op" do
      first =
        phoenix_project()
        |> Igniter.compose_task("phoenix_prodmin.install", [])
        |> apply_igniter!()

      first_runtime = read(first, "config/runtime.exs")
      first_backup = read(first, "config/.runtime.exs.bak")

      {:ok, second, %{notices: notices}} =
        first
        |> Igniter.compose_task("phoenix_prodmin.install", [])
        |> apply_igniter()

      assert read(second, "config/runtime.exs") == first_runtime
      assert read(second, "config/.runtime.exs.bak") == first_backup

      assert Enum.any?(notices, &String.contains?(&1, "already installed"))
    end

    test "--force overwrites runtime.exs but does not clobber the backup" do
      first =
        phoenix_project()
        |> Igniter.compose_task("phoenix_prodmin.install", [])
        |> apply_igniter!()

      first_backup = read(first, "config/.runtime.exs.bak")

      second =
        first
        |> Igniter.compose_task("phoenix_prodmin.install", ["--force"])
        |> apply_igniter!()

      assert read(second, "config/runtime.exs") =~ "# Generated by phoenix_prodmin"
      assert read(second, "config/.runtime.exs.bak") == first_backup
    end
  end

  describe "error cases" do
    test "fails clearly when host project is not Phoenix" do
      files = %{
        "mix.exs" => """
        defmodule Plain.MixProject do
          use Mix.Project

          def project do
            [app: :plain, version: "0.1.0", elixir: "~> 1.17", deps: deps()]
          end

          def application, do: [extra_applications: [:logger]]

          defp deps, do: []
        end
        """
      }

      {:error, issues} =
        test_project(app_name: :plain, files: files)
        |> Igniter.compose_task("phoenix_prodmin.install", [])
        |> apply_igniter()

      assert Enum.any?(issues, &String.contains?(&1, "Phoenix"))
    end

    test "fails clearly when runtime.exs is missing" do
      files = %{
        "mix.exs" => """
        defmodule Myapp.MixProject do
          use Mix.Project

          def project do
            [app: :myapp, version: "0.1.0", elixir: "~> 1.17", deps: deps()]
          end

          def application, do: [extra_applications: [:logger]]

          defp deps, do: [{:phoenix, "~> 1.7"}]
        end
        """
      }

      {:error, issues} =
        test_project(app_name: :myapp, files: files)
        |> Igniter.compose_task("phoenix_prodmin.install", [])
        |> apply_igniter()

      assert Enum.any?(issues, &String.contains?(&1, "runtime.exs"))
    end
  end

  defp read(igniter, path) do
    Map.fetch!(igniter.assigns[:test_files], path)
  end

  defp install_and_extract_secret(igniter) do
    igniter =
      igniter
      |> Igniter.compose_task("phoenix_prodmin.install", [])
      |> apply_igniter!()

    [_, key] = Regex.run(~r/secret_key_base: "([^"]+)"/, read(igniter, "config/runtime.exs"))
    key
  end
end
